export const OPEN_BANK_ACCOUNT = 'OPEN_BANK_ACCOUNT'
export const CLOSE_BANK_ACCOUNT = 'CLOSE_BANK_ACCOUNT'
export const GET_BANK_ACCOUNTS ="GET_BANK_ACCOUNTS"
export const EDIT_BANK_BALANCE ="EDIT_BANK_BALANCE"
export const WITHDRAWFUNDS_BANK ="WITHDRAWFUNDS_BANK"
